modLoader = "javafml"
loaderVersion = "[47,)"
license = "ARR"
issueTrackerURL = "https://github.com/terrarium-earth/Tempad/issues"

[[mods]]
modId = "tempad"
version = "${version}"
displayName = "Tempad"
displayURL = "https://modrinth.com/mod/tempad"
logoFile = "icon.png"
authors = "CodexAdrian"
credits = "MsRandom1, ThatGravyBoat, abused_master, Kekie6, Jooosh"
description = "Create a portal to anywhere from anywhere!"

[[dependencies.tempad]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "NONE"
side = "BOTH"
